id: AC6BB94F2
title: Prayer for the Land of Great Bliss Practice
type: translation
pechas:
- I4CA831B4
- IAE502A22
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:54:41.164764
  last_modified_at: 2023-01-04 11:54:41.164769
  collections:
  - Fourteenth Karmapa Series
  - Works of Tibetan Masters
alignment_to_base:
  I4CA831B4/ED0F: CD63
  IAE502A22/A14C: CD63
